### ISSUE TITLE
How to Get All order_id's

### ISSUE THREAD

**Issue by iflairemp264** [MultiSafepay/multisafepay-postman-collection#2]
How can i get all Transaction History???

**Comment by Raul-MultiSafepay** [comment]
Hi, sorry but at the moment is not supported, we have this feature on our roadmap but still in progress with no any ETA at the moment.
We will update the our documentation when this is done, for now you can only do this:
https://docs.multisafepay.com/api/#retrieve-an-order

**Comment by Raul-MultiSafepay** [comment]
For now i will close this issue. Thanks for your feedback
